linter:

  rules:
    - avoid_print
    - avoid_unnecessary_containers
    - avoid_web_libraries_in_flutter
    - no_logic_in_create_state
    - prefer_const_declarations
    - sized_box_for_whitespace
    - use_full_hex_values_for_flutter_colors

analyzer:

  errors:
    todo: ignore
    use_build_context_synchronously: ignore
  plugins:
    - dart_code_linter

dart_code_linter:
  metrics:
    cyclomatic-complexity: 20
    halstead-volume: 150
    lines-of-code: 100
    maintainability-index: 50
    maximum-nesting-level: 5
    number-of-methods: 10
    number-of-parameters: 6
    source-lines-of-code: 120
    weight-of-class: 0.33
    number-of-arguments: 4
  metrics-exclude:
    - test/**
  rules:
    - prefer-conditional-expressions
    - prefer-trailing-comma
    - no-empty-block
    - avoid-unnecessary-setstate
    - avoid-wrapping-in-padding
    - prefer-const-border-radius
    - prefer-extracting-callbacks
    - avoid-ignoring-return-values
    - avoid-returning-widgets
    - prefer-single-widget-per-file
    - avoid-unused-parameters
    - binary-expression-operand-order
    - member-ordering
    - newline-before-return
    - no-boolean-literal-compare
    - no-equal-then-else
    - prefer-correct-identifier-length:
        - exceptions: ["z"]
        - max-identifier-length: 30
        - min-identifier-length: 4
        
    - prefer-correct-type-name:
        - excluded: ["exampleExclude"]
        - min-length: 3
        - max-length: 40

    # End rules
