name: double_v_partners
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_native_splash: ^2.4.5
  shared_preferences: ^2.5.2
  flutter_dotenv: ^5.2.1
  http: ^1.3.0
  intl: ^0.19.0
  uuid: ^4.5.1
  toastification: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  dart_code_linter: ^2.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.7
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
        - asset: assets/fonts/Lato-Light.ttf
        - asset: assets/fonts/Lato-Black.ttf
  assets:
    - assets/
